[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --no-audit --no-fund"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx next start --hostname 0.0.0.0 --port $PORT"
